import { createHash } from "node:crypto";
import { readFile,writeFile,mkdir } from "node:fs/promises";
import { dirname,resolve } from "node:path";
import {
  detectBudgetDocumentTabularRegions,
  locateBudgetDocumentPages,
  observeDocumentSignals,
  reconstructBudgetDocumentPhysicalColumnHypotheses,
  reconstructBudgetDocumentStructure,
} from "../../../../domain/budget-document-location";
import { canonicalJson,reconstructBudgetTable } from "../../../../domain/budget-table-reconstruction";
import type { BudgetTableReconstructionInput,BudgetTableReconstructionResult } from "../../../../domain/budget-table-reconstruction";
import { pdfjsPhysicalDocumentReader } from "../index";

interface Arguments{readonly input:string;readonly expectedSha256:string;readonly pages:ReadonlyArray<number>;readonly output:string}
interface DiagnosticOutput{readonly schemaVersion:1;readonly requestedPageNumbers:ReadonlyArray<number>;readonly selectedPages:BudgetTableReconstructionResult["pages"];readonly reconstruction:BudgetTableReconstructionResult}
function argumentsFrom(command:ReadonlyArray<string>):Arguments{const values=new Map<string,string>();for(let index=0;index<command.length;index+=2){const name=command[index];const value=command[index+1];if(!name?.startsWith("--")||value===undefined)throw new Error("expected paired --name value arguments");values.set(name,value)}const input=values.get("--input");const expectedSha256=values.get("--expected-sha256");const pages=values.get("--pages");const output=values.get("--output");if(!input||!expectedSha256||!pages||!output)throw new Error("required arguments: --input, --expected-sha256, --pages, --output");if(!/^[a-f0-9]{64}$/i.test(expectedSha256))throw new Error("expected SHA-256 must contain 64 hexadecimal characters");const pageNumbers=[...new Set(pages.split(",").map(value=>Number(value.trim())))].sort((a,b)=>a-b);if(pageNumbers.length===0||pageNumbers.some(value=>!Number.isSafeInteger(value)||value<=0))throw new Error("pages must be a comma-separated list of positive integers");return{input:resolve(input),expectedSha256:expectedSha256.toLowerCase(),pages:pageNumbers,output:resolve(output)}}
async function reconstructOnce(path:string,expectedSha256:string):Promise<BudgetTableReconstructionResult>{const file=await readFile(path);const bytes=new Uint8Array(file);const actual=createHash("sha256").update(bytes).digest("hex");if(actual!==expectedSha256)throw new Error(`input SHA-256 mismatch: expected ${expectedSha256}, observed ${actual}`);const physicalRead=await pdfjsPhysicalDocumentReader.read(bytes);const observation=observeDocumentSignals(physicalRead);const pageLocation=locateBudgetDocumentPages(observation);const structureReconstruction=reconstructBudgetDocumentStructure({physicalRead,pageLocation});let columnEvidence:BudgetTableReconstructionInput["columnEvidence"];try{const tabularRegionDetection=detectBudgetDocumentTabularRegions({structureReconstruction});const result=reconstructBudgetDocumentPhysicalColumnHypotheses({structureReconstruction,tabularRegionDetection});columnEvidence=result.status==="failed"?{availability:"unavailable",reasonCode:"physical_column_hypothesis_reconstruction_failed"}:{availability:"available",result}}catch{columnEvidence={availability:"unavailable",reasonCode:"physical_column_hypothesis_reconstruction_threw"}}return reconstructBudgetTable({physicalRead,pageLocation,structureReconstruction,columnEvidence})}
function diagnostic(result:BudgetTableReconstructionResult,pages:ReadonlyArray<number>):DiagnosticOutput{return{schemaVersion:1,requestedPageNumbers:pages,selectedPages:result.pages.filter(page=>pages.includes(page.pageNumber)),reconstruction:result}}
async function main():Promise<void>{const args=argumentsFrom(process.argv.slice(2));const first=diagnostic(await reconstructOnce(args.input,args.expectedSha256),args.pages);const second=diagnostic(await reconstructOnce(args.input,args.expectedSha256),args.pages);const firstBytes=canonicalJson(first);const secondBytes=canonicalJson(second);if(firstBytes!==secondBytes)throw new Error("two fresh executions produced different canonical bytes");if(first.reconstruction.canonicalFingerprint!==second.reconstruction.canonicalFingerprint)throw new Error("two fresh executions produced different reconstruction fingerprints");await mkdir(dirname(args.output),{recursive:true});await writeFile(args.output,firstBytes,"utf8");console.log(canonicalJson({output:args.output,canonicalFingerprint:first.reconstruction.canonicalFingerprint,byteIdentical:true,selectedPageNumbers:first.selectedPages.map(page=>page.pageNumber),status:first.reconstruction.status,structuralIssues:first.reconstruction.structuralIssues,completeness:first.reconstruction.completeness}))}
await main();
