import type { ReconstructedBudgetDocumentPage, ReconstructedHorizontalSegment, ReconstructedPhysicalLine } from "../structure-reconstruction/budget-document-structure-reconstruction.types";
import type { PhysicalColumnHypothesis, PhysicalColumnHypothesisReconstructionRegion } from "../physical-column-hypothesis-reconstruction/budget-document-physical-column-hypothesis-reconstruction.types";
import { findCompatibleStructureReconstructionContract } from "../tabular-region-detection/tabular-region-detection-source-contracts";
import { computeStructureReconstructionContextFingerprint } from "../structure-reconstruction/structure-reconstruction-context-fingerprint";
import { findCompatibleTabularRegionDetectionContract } from "../physical-column-hypothesis-reconstruction/physical-column-hypothesis-reconstruction-source-contracts";
import { computeTabularRegionDetectionIdentityFingerprint, buildTabularRegionDetectionIdentityFingerprintInput, computeTabularRegionDetectionContentFingerprint } from "../tabular-region-detection/tabular-region-detection-context-fingerprint";
import { VERTICAL_ALIGNMENT_OBSERVATION_RULE_ID, VERTICAL_ALIGNMENT_OBSERVATION_RULE_VERSION } from "../tabular-region-detection/vertical-alignment-observation";
import { TABULAR_REGION_FORMATION_RULE_ID, TABULAR_REGION_FORMATION_RULE_VERSION } from "../tabular-region-detection/tabular-region-formation";
import { BUDGET_DOCUMENT_TABULAR_REGION_DETECTION_PROFILE_V1 } from "../tabular-region-detection/tabular-region-detection-profile";
import { buildPhysicalColumnHypothesisReconstructionIdentityFingerprintInput, computePhysicalColumnHypothesisReconstructionContentFingerprint, computePhysicalColumnHypothesisReconstructionIdentityFingerprint } from "../physical-column-hypothesis-reconstruction/physical-column-hypothesis-reconstruction-context-fingerprint";
import { BUDGET_DOCUMENT_PHYSICAL_COLUMN_HYPOTHESIS_RECONSTRUCTION_PROFILE_V1 } from "../physical-column-hypothesis-reconstruction/physical-column-hypothesis-reconstruction-profile";
import { PHYSICAL_VERTICAL_BAND_CONSTRUCTION_RULE_ID, PHYSICAL_VERTICAL_BAND_CONSTRUCTION_RULE_VERSION } from "../physical-column-hypothesis-reconstruction/physical-vertical-band-construction";
import { PHYSICAL_COLUMN_HYPOTHESIS_FORMATION_RULE_ID as COLUMN_RULE_ID, PHYSICAL_COLUMN_HYPOTHESIS_FORMATION_RULE_VERSION as COLUMN_RULE_VERSION } from "../physical-column-hypothesis-reconstruction/physical-column-hypothesis-formation";
import type { BudgetDocumentPhysicalCellHypothesisFormationInput, BudgetDocumentPhysicalCellHypothesisFormationResult, GlobalPhysicalCellHypothesisFormationMetrics, GroupPhysicalCellHypothesisFormationMetrics, PagePhysicalCellHypothesisFormationMetrics, PhysicalCellHypothesis, PhysicalCellHypothesisFormationGroup, PhysicalCellHypothesisFormationPage, PhysicalCellHypothesisFormationRegion, PhysicalCellHypothesisSegmentDisposition, PhysicalGeometryBounds, PhysicalGridIntersection, RegionPhysicalCellHypothesisFormationMetrics } from "./budget-document-physical-cell-hypothesis-formation.types";
import { BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_ENGINE_NAME, BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_ENGINE_VERSION, BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_SCHEMA_VERSION, PHYSICAL_CELL_HYPOTHESIS_FORMATION_CONTEXT_FINGERPRINT_VERSION } from "./budget-document-physical-cell-hypothesis-formation.types";
import { computeContentFingerprint, computeIdentityFingerprint } from "./physical-cell-hypothesis-formation-context-fingerprint";
import { computeCellHypothesisKey, computeGridIntersectionKey, computeGroupProcessedKey, computePageProcessedKey, computeRegionProcessedKey } from "./physical-cell-hypothesis-formation-keys";
import { LIMITATIONS, PHYSICAL_CELL_HYPOTHESIS_FORMATION_RULE_ID, PHYSICAL_CELL_HYPOTHESIS_FORMATION_RULE_VERSION, PHYSICAL_GRID_FORMATION_RULE_ID, PHYSICAL_GRID_FORMATION_RULE_VERSION, PROFILE } from "./physical-cell-hypothesis-formation-profile";
import { canonicalizePhysicalCellFormationBounds } from "./physical-cell-hypothesis-formation-output-geometry-canonicalization";
import { problem } from "./physical-cell-hypothesis-formation-technical-problem";

function bounds(leftPoints:number,topPoints:number,rightPoints:number,bottomPoints:number): PhysicalGeometryBounds { return { leftPoints,topPoints,rightPoints,bottomPoints,widthPoints:rightPoints-leftPoints,heightPoints:bottomPoints-topPoints,centerXPoints:(leftPoints+rightPoints)/2,centerYPoints:(topPoints+bottomPoints)/2 }; }
function coherent(g: PhysicalGeometryBounds): boolean { return [g.leftPoints,g.topPoints,g.rightPoints,g.bottomPoints,g.widthPoints,g.heightPoints,g.centerXPoints,g.centerYPoints].every(Number.isFinite) && g.rightPoints>g.leftPoints && g.bottomPoints>g.topPoints && g.widthPoints===g.rightPoints-g.leftPoints && g.heightPoints===g.bottomPoints-g.topPoints && g.centerXPoints===(g.leftPoints+g.rightPoints)/2 && g.centerYPoints===(g.topPoints+g.bottomPoints)/2; }
function contained(s: PhysicalGeometryBounds,g: PhysicalGeometryBounds): boolean { return s.leftPoints>=g.leftPoints&&s.rightPoints<=g.rightPoints&&s.topPoints>=g.topPoints&&s.bottomPoints<=g.bottomPoints; }
function overlaps(a: PhysicalGeometryBounds,b: PhysicalGeometryBounds): boolean { return Math.min(a.rightPoints,b.rightPoints)-Math.max(a.leftPoints,b.leftPoints)>0&&Math.min(a.bottomPoints,b.bottomPoints)-Math.max(a.topPoints,b.topPoints)>0; }
function segmentBounds(s: ReconstructedHorizontalSegment): PhysicalGeometryBounds { return bounds(s.leftPoints,s.topPoints,s.rightPoints,s.bottomPoints); }
function lineBounds(s: ReconstructedPhysicalLine): PhysicalGeometryBounds { return bounds(s.leftPoints,s.topPoints,s.rightPoints,s.bottomPoints); }
function columnBounds(s: PhysicalColumnHypothesis): PhysicalGeometryBounds { return bounds(s.leftPoints,s.topPoints,s.rightPoints,s.bottomPoints); }

function regionMetrics(intersections: ReadonlyArray<PhysicalGridIntersection>, cells: ReadonlyArray<PhysicalCellHypothesis>, dispositions: ReadonlyArray<PhysicalCellHypothesisSegmentDisposition>, lineCount:number,columnCount:number,problemCount:number): RegionPhysicalCellHypothesisFormationMetrics { return {
  sourceLineCount:lineCount,sourcePhysicalColumnHypothesisCount:columnCount,totalGridIntersectionCount:intersections.length,
  cellHypothesisFormedIntersectionCount:intersections.filter(x=>x.status==="cell_hypothesis_formed").length,emptyGridIntersectionCount:intersections.filter(x=>x.status==="empty").length,ambiguousGridIntersectionCount:intersections.filter(x=>x.status==="unresolved_segment_association_ambiguity").length,formationFailedGridIntersectionCount:intersections.filter(x=>x.status==="unresolved_technical_failure").length,
  totalRegionSegmentCount:dispositions.length,includedSegmentCount:dispositions.filter(x=>x.status==="included_in_physical_cell_hypothesis").length,outsideSegmentCount:dispositions.filter(x=>x.status==="outside_all_physical_cell_hypotheses").length,inheritedAmbiguousSegmentCount:dispositions.filter(x=>x.status==="unresolved_inherited_column_ambiguity").length,partialIntersectionSegmentCount:dispositions.filter(x=>x.status==="unresolved_partial_grid_intersection").length,multipleClaimSegmentCount:dispositions.filter(x=>x.status==="unresolved_multiple_grid_intersection_claim").length,sourceContractInconsistentSegmentCount:dispositions.filter(x=>x.status==="unresolved_source_contract_inconsistency").length,formationFailedSegmentCount:dispositions.filter(x=>x.status==="unresolved_cell_hypothesis_formation_failed").length,
  cellHypothesisCount:cells.length,multiSegmentCellHypothesisCount:cells.filter(x=>x.segmentKeys.length>1).length,technicalProblemCount:problemCount,
}; }

function invalidRegion(regionKey:string,pageNumber:number,regionProcessedKey:string,lineCount:number,columnCount:number,code:"source_line_reference_invalid"|"source_segment_reference_invalid"|"source_line_geometry_degenerate"|"source_physical_column_hypothesis_geometry_degenerate"|"source_geometry_incoherent"|"source_valid_column_hypotheses_overlap"|"source_segment_claimed_by_multiple_valid_column_hypotheses", lineKey:string|null=null,columnKey:string|null=null): PhysicalCellHypothesisFormationRegion { const p=problem(code,"source_validation",{pageNumber,regionKey,lineKey,physicalColumnHypothesisKey:columnKey}); return {regionProcessedKey,sourceRegionKey:regionKey,pageNumber,status:"region_not_processable",gridIntersections:[],cellHypotheses:[],segmentDispositions:[],technicalProblems:[p],metrics:regionMetrics([],[],[],lineCount,columnCount,1),profileId:PROFILE.profileId,profileVersion:PROFILE.profileVersion}; }

function processRegion(sourceRegion: PhysicalColumnHypothesisReconstructionRegion, page: ReconstructedBudgetDocumentPage, regionProcessedKey:string): PhysicalCellHypothesisFormationRegion {
  const lineByKey=new Map(page.lines.map(x=>[x.lineKey,x])); const segmentByKey=new Map(page.segments.map(x=>[x.segmentKey,x]));
  const regionLineKeys=[...new Set(sourceRegion.hypotheses.flatMap(x=>x.lineKeys).concat(sourceRegion.segmentDispositions.map(x=>x.lineKey)))];
  const lines=regionLineKeys.map(k=>lineByKey.get(k)).filter((x):x is ReconstructedPhysicalLine=>x!==undefined).sort((a,b)=>a.verticalOrder-b.verticalOrder||a.lineKey.localeCompare(b.lineKey));
  const columns=[...sourceRegion.hypotheses].sort((a,b)=>a.order-b.order||a.leftPoints-b.leftPoints||a.hypothesisKey.localeCompare(b.hypothesisKey));
  if(lines.length!==regionLineKeys.length)return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_line_reference_invalid");
  for(const line of lines){ const b=lineBounds(line); if(b.widthPoints<=0||b.heightPoints<=0)return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_line_geometry_degenerate",line.lineKey); if(!coherent(b))return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_geometry_incoherent",line.lineKey); }
  for(const col of columns){ const b=columnBounds(col); if(b.widthPoints<=0||b.heightPoints<=0)return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_physical_column_hypothesis_geometry_degenerate",null,col.hypothesisKey); if(!coherent(b))return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_geometry_incoherent",null,col.hypothesisKey); }
  for(let i=0;i<columns.length;i++)for(let j=i+1;j<columns.length;j++){ if(Math.min(columns[i].rightPoints,columns[j].rightPoints)-Math.max(columns[i].leftPoints,columns[j].leftPoints)>0)return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_valid_column_hypotheses_overlap"); if(columns[i].segmentKeys.some(k=>columns[j].segmentKeys.includes(k)))return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_segment_claimed_by_multiple_valid_column_hypotheses"); }
  const segmentKeys=[...new Set(lines.flatMap(x=>x.segmentKeys))]; const segments=segmentKeys.map(k=>segmentByKey.get(k)).filter((x):x is ReconstructedHorizontalSegment=>x!==undefined).sort((a,b)=>a.horizontalOrder-b.horizontalOrder||a.segmentKey.localeCompare(b.segmentKey));
  if(segments.length!==segmentKeys.length)return invalidRegion(sourceRegion.sourceRegionKey,page.pageNumber,regionProcessedKey,lines.length,columns.length,"source_segment_reference_invalid");
  const inherited=new Map(sourceRegion.segmentDispositions.filter(x=>x.status==="unresolved_physical_column_hypothesis_ambiguity").map(x=>[x.segmentKey,x]));
  if(lines.length===0||columns.length===0){ const dispositions=segments.map(s=>{const a=inherited.get(s.segmentKey); return a?{status:"unresolved_inherited_column_ambiguity" as const,segmentKey:s.segmentKey,lineKey:s.lineKey,conflictingCandidateHypothesisKeys:a.conflictingCandidateHypothesisKeys}:{status:"outside_all_physical_cell_hypotheses" as const,segmentKey:s.segmentKey,lineKey:s.lineKey};}); return {regionProcessedKey,sourceRegionKey:sourceRegion.sourceRegionKey,pageNumber:page.pageNumber,status:dispositions.some(x=>x.status==="unresolved_inherited_column_ambiguity")?"formed_with_ambiguities":"no_physical_grid",gridIntersections:[],cellHypotheses:[],segmentDispositions:dispositions,technicalProblems:[],metrics:regionMetrics([],[],dispositions,lines.length,columns.length,0),profileId:PROFILE.profileId,profileVersion:PROFILE.profileVersion}; }
  const identities=lines.flatMap(line=>columns.map(column=>({line,column,key:computeGridIntersectionKey(regionProcessedKey,line.lineKey,column.hypothesisKey),grid:bounds(column.leftPoints,line.topPoints,column.rightPoints,line.bottomPoints)})));
  const byLine=new Map<string,typeof identities>(); for(const i of identities){const a=byLine.get(i.line.lineKey)??[];a.push(i);byLine.set(i.line.lineKey,a);}
  const containedByIntersection=new Map<string,ReconstructedHorizontalSegment[]>(); const segmentDisposition=new Map<string,PhysicalCellHypothesisSegmentDisposition>(); const partialByIntersection=new Map<string,string[]>(); const multipleByIntersection=new Map<string,{segments:string[],others:Set<string>}>();
  for(const s of segments){ const inheritedDisposition=inherited.get(s.segmentKey); if(inheritedDisposition){segmentDisposition.set(s.segmentKey,{status:"unresolved_inherited_column_ambiguity",segmentKey:s.segmentKey,lineKey:s.lineKey,conflictingCandidateHypothesisKeys:inheritedDisposition.conflictingCandidateHypothesisKeys});continue;} const candidates=byLine.get(s.lineKey)??[]; const full=candidates.filter(i=>contained(segmentBounds(s),i.grid)); const partial=candidates.filter(i=>!contained(segmentBounds(s),i.grid)&&overlaps(segmentBounds(s),i.grid)); if(partial.length){segmentDisposition.set(s.segmentKey,{status:"unresolved_partial_grid_intersection",segmentKey:s.segmentKey,lineKey:s.lineKey,partiallyIntersectedGridIntersectionKeys:partial.map(x=>x.key)});for(const i of partial){const a=partialByIntersection.get(i.key)??[];a.push(s.segmentKey);partialByIntersection.set(i.key,a);}continue;} if(full.length>1){const keys=full.map(x=>x.key);segmentDisposition.set(s.segmentKey,{status:"unresolved_multiple_grid_intersection_claim",segmentKey:s.segmentKey,lineKey:s.lineKey,claimingGridIntersectionKeys:keys});for(const i of full){const a=multipleByIntersection.get(i.key)??{segments:[],others:new Set<string>()};a.segments.push(s.segmentKey);keys.filter(k=>k!==i.key).forEach(k=>a.others.add(k));multipleByIntersection.set(i.key,a);}continue;} if(full.length===1){const a=containedByIntersection.get(full[0].key)??[];a.push(s);containedByIntersection.set(full[0].key,a);continue;} segmentDisposition.set(s.segmentKey,{status:"outside_all_physical_cell_hypotheses",segmentKey:s.segmentKey,lineKey:s.lineKey}); }
  const cells:PhysicalCellHypothesis[]=[]; const intersections:PhysicalGridIntersection[]=[];
  for(const i of identities){ const base={gridIntersectionKey:i.key,sourceLineKey:i.line.lineKey,sourcePhysicalColumnHypothesisKey:i.column.hypothesisKey,sourceRegionKey:sourceRegion.sourceRegionKey,pageNumber:page.pageNumber,rowOrder:i.line.verticalOrder,columnOrder:i.column.order,gridBounds:canonicalizePhysicalCellFormationBounds(i.grid),gridFormationRuleId:PHYSICAL_GRID_FORMATION_RULE_ID,gridFormationRuleVersion:PHYSICAL_GRID_FORMATION_RULE_VERSION,profileId:PROFILE.profileId,profileVersion:PROFILE.profileVersion}; const partial=partialByIntersection.get(i.key); if(partial){intersections.push({...base,status:"unresolved_segment_association_ambiguity",ambiguityReason:"partial_segment_intersection",partiallyIntersectingSegmentKeys:partial.sort()});continue;} const multiple=multipleByIntersection.get(i.key); if(multiple){intersections.push({...base,status:"unresolved_segment_association_ambiguity",ambiguityReason:"segment_claimed_by_multiple_intersections",disputedSegmentKeys:multiple.segments.sort(),conflictingGridIntersectionKeys:[...multiple.others].sort()});continue;} const members=(containedByIntersection.get(i.key)??[]).sort((a,b)=>a.horizontalOrder-b.horizontalOrder||a.segmentKey.localeCompare(b.segmentKey)); if(!members.length){intersections.push({...base,status:"empty"});continue;} const observed=canonicalizePhysicalCellFormationBounds(bounds(Math.min(...members.map(x=>x.leftPoints)),Math.min(...members.map(x=>x.topPoints)),Math.max(...members.map(x=>x.rightPoints)),Math.max(...members.map(x=>x.bottomPoints)))); if(!contained(observed,base.gridBounds)){intersections.push({...base,status:"unresolved_segment_association_ambiguity",ambiguityReason:"observed_content_outside_grid_bounds",evidenceSegmentKeys:members.map(x=>x.segmentKey),observedContentBounds:observed});members.forEach(s=>segmentDisposition.set(s.segmentKey,{status:"unresolved_partial_grid_intersection",segmentKey:s.segmentKey,lineKey:s.lineKey,partiallyIntersectedGridIntersectionKeys:[i.key]}));continue;} const cellKey=computeCellHypothesisKey(i.key,members.map(x=>x.segmentKey)); cells.push({cellHypothesisKey:cellKey,gridIntersectionKey:i.key,observedContentBounds:observed,segmentKeys:members.map(x=>x.segmentKey),cellFormationRuleId:PHYSICAL_CELL_HYPOTHESIS_FORMATION_RULE_ID,cellFormationRuleVersion:PHYSICAL_CELL_HYPOTHESIS_FORMATION_RULE_VERSION,profileId:PROFILE.profileId,profileVersion:PROFILE.profileVersion}); intersections.push({...base,status:"cell_hypothesis_formed",cellHypothesisKey:cellKey});members.forEach(s=>segmentDisposition.set(s.segmentKey,{status:"included_in_physical_cell_hypothesis",segmentKey:s.segmentKey,lineKey:s.lineKey,gridIntersectionKey:i.key,cellHypothesisKey:cellKey})); }
  const dispositions=segments.map(s=>segmentDisposition.get(s.segmentKey)!); const metrics=regionMetrics(intersections,cells,dispositions,lines.length,columns.length,0); const hasAmb=metrics.ambiguousGridIntersectionCount>0||metrics.inheritedAmbiguousSegmentCount>0||metrics.multipleClaimSegmentCount>0; const status=hasAmb?"formed_with_ambiguities":cells.length===0?"grid_without_cell_hypotheses":"formed"; return {regionProcessedKey,sourceRegionKey:sourceRegion.sourceRegionKey,pageNumber:page.pageNumber,status,gridIntersections:intersections,cellHypotheses:cells,segmentDispositions:dispositions,technicalProblems:[],metrics,profileId:PROFILE.profileId,profileVersion:PROFILE.profileVersion};
}

function pageMetrics(regions:ReadonlyArray<PhysicalCellHypothesisFormationRegion>):PagePhysicalCellHypothesisFormationMetrics { const sums=regions.map(x=>x.metrics);return {totalRegionCount:regions.length,formedRegionCount:regions.filter(x=>x.status==="formed").length,formedWithAmbiguitiesRegionCount:regions.filter(x=>x.status==="formed_with_ambiguities").length,formedWithProblemsRegionCount:regions.filter(x=>x.status==="formed_with_problems").length,gridWithoutCellHypothesesRegionCount:regions.filter(x=>x.status==="grid_without_cell_hypotheses").length,noPhysicalGridRegionCount:regions.filter(x=>x.status==="no_physical_grid").length,regionNotProcessableCount:regions.filter(x=>x.status==="region_not_processable").length,gridIntersectionCount:sums.reduce((a,x)=>a+x.totalGridIntersectionCount,0),emptyGridIntersectionCount:sums.reduce((a,x)=>a+x.emptyGridIntersectionCount,0),cellHypothesisCount:sums.reduce((a,x)=>a+x.cellHypothesisCount,0),multiSegmentCellHypothesisCount:sums.reduce((a,x)=>a+x.multiSegmentCellHypothesisCount,0),segmentCount:sums.reduce((a,x)=>a+x.totalRegionSegmentCount,0),includedSegmentCount:sums.reduce((a,x)=>a+x.includedSegmentCount,0),ambiguousSegmentCount:sums.reduce((a,x)=>a+x.inheritedAmbiguousSegmentCount+x.partialIntersectionSegmentCount+x.multipleClaimSegmentCount,0),formationFailedSegmentCount:sums.reduce((a,x)=>a+x.formationFailedSegmentCount,0),technicalProblemCount:sums.reduce((a,x)=>a+x.technicalProblemCount,0)}; }
function groupMetrics(pages:ReadonlyArray<PhysicalCellHypothesisFormationPage>):GroupPhysicalCellHypothesisFormationMetrics {const s=pages.map(x=>x.metrics);return {totalPageCount:pages.length,formedPageCount:pages.filter(x=>x.status==="formed").length,formedWithAmbiguitiesPageCount:pages.filter(x=>x.status==="formed_with_ambiguities").length,formedWithProblemsPageCount:pages.filter(x=>x.status==="formed_with_problems").length,noPhysicalGridPageCount:pages.filter(x=>x.status==="no_physical_grid").length,pageNotProcessableCount:pages.filter(x=>x.status==="page_not_processable").length,gridIntersectionCount:s.reduce((a,x)=>a+x.gridIntersectionCount,0),emptyGridIntersectionCount:s.reduce((a,x)=>a+x.emptyGridIntersectionCount,0),cellHypothesisCount:s.reduce((a,x)=>a+x.cellHypothesisCount,0),multiSegmentCellHypothesisCount:s.reduce((a,x)=>a+x.multiSegmentCellHypothesisCount,0),segmentCount:s.reduce((a,x)=>a+x.segmentCount,0),includedSegmentCount:s.reduce((a,x)=>a+x.includedSegmentCount,0),ambiguousSegmentCount:s.reduce((a,x)=>a+x.ambiguousSegmentCount,0),formationFailedSegmentCount:s.reduce((a,x)=>a+x.formationFailedSegmentCount,0),technicalProblemCount:s.reduce((a,x)=>a+x.technicalProblemCount,0)};}
function globalMetrics(groups:ReadonlyArray<PhysicalCellHypothesisFormationGroup>):GlobalPhysicalCellHypothesisFormationMetrics {const s=groups.map(x=>x.metrics);return {receivedGroupCount:groups.length,formedGroupCount:groups.filter(x=>x.status==="formed").length,formedWithAmbiguitiesGroupCount:groups.filter(x=>x.status==="formed_with_ambiguities").length,formedWithProblemsGroupCount:groups.filter(x=>x.status==="formed_with_problems").length,noPhysicalGridGroupCount:groups.filter(x=>x.status==="no_physical_grid").length,groupNotProcessableCount:groups.filter(x=>x.status==="group_not_processable").length,candidatePageCount:s.reduce((a,x)=>a+x.totalPageCount,0),candidateRegionCount:groups.reduce((a,g)=>a+g.pages.reduce((b,p)=>b+p.metrics.totalRegionCount,0),0),gridIntersectionCount:s.reduce((a,x)=>a+x.gridIntersectionCount,0),emptyGridIntersectionCount:s.reduce((a,x)=>a+x.emptyGridIntersectionCount,0),cellHypothesisCount:s.reduce((a,x)=>a+x.cellHypothesisCount,0),multiSegmentCellHypothesisCount:s.reduce((a,x)=>a+x.multiSegmentCellHypothesisCount,0),segmentCount:s.reduce((a,x)=>a+x.segmentCount,0),includedSegmentCount:s.reduce((a,x)=>a+x.includedSegmentCount,0),ambiguousSegmentCount:s.reduce((a,x)=>a+x.ambiguousSegmentCount,0),formationFailedSegmentCount:s.reduce((a,x)=>a+x.formationFailedSegmentCount,0),technicalProblemCount:s.reduce((a,x)=>a+x.technicalProblemCount,0)};}

function buildResult(input:BudgetDocumentPhysicalCellHypothesisFormationInput,identity:string,groups:ReadonlyArray<PhysicalCellHypothesisFormationGroup>,technicalProblems:BudgetDocumentPhysicalCellHypothesisFormationResult["technicalProblems"],status:BudgetDocumentPhysicalCellHypothesisFormationResult["status"]):BudgetDocumentPhysicalCellHypothesisFormationResult {const s=input.structureReconstruction,t=input.tabularRegionDetection,c=input.physicalColumnHypothesisReconstruction;const metrics=globalMetrics(groups);const formationContextFingerprint=computeContentFingerprint(identity,{status,groups,technicalProblems,metrics,limitations:LIMITATIONS});return {schemaVersion:BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_SCHEMA_VERSION,formationEngineName:BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_ENGINE_NAME,formationEngineVersion:BUDGET_DOCUMENT_PHYSICAL_CELL_HYPOTHESIS_FORMATION_ENGINE_VERSION,formationProfileId:PROFILE.profileId,formationProfileVersion:PROFILE.profileVersion,formationContextFingerprintVersion:PHYSICAL_CELL_HYPOTHESIS_FORMATION_CONTEXT_FINGERPRINT_VERSION,formationContextFingerprint,sourceByteHash:s.sourceByteHash,sourceStructureReconstructionSchemaVersion:s.schemaVersion,sourceStructureReconstructorName:s.reconstructorName,sourceStructureReconstructorVersion:s.reconstructorVersion,sourceStructureReconstructionProfileId:s.reconstructionProfileId,sourceStructureReconstructionProfileVersion:s.reconstructionProfileVersion,sourceStructureReconstructionContextFingerprintVersion:s.reconstructionContextFingerprintVersion,sourceStructureReconstructionContextFingerprint:s.reconstructionContextFingerprint,sourceTabularRegionDetectionSchemaVersion:t.schemaVersion,sourceTabularRegionDetectorName:t.detectorName,sourceTabularRegionDetectorVersion:t.detectorVersion,sourceTabularRegionDetectionProfileId:t.detectionProfileId,sourceTabularRegionDetectionProfileVersion:t.detectionProfileVersion,sourceTabularRegionDetectionContextFingerprintVersion:t.detectionContextFingerprintVersion,sourceTabularRegionDetectionContextFingerprint:t.detectionContextFingerprint,sourcePhysicalColumnHypothesisReconstructionSchemaVersion:c.schemaVersion,sourcePhysicalColumnHypothesisReconstructorName:c.reconstructorName,sourcePhysicalColumnHypothesisReconstructorVersion:c.reconstructorVersion,sourcePhysicalColumnHypothesisReconstructionProfileId:c.reconstructionProfileId,sourcePhysicalColumnHypothesisReconstructionProfileVersion:c.reconstructionProfileVersion,sourcePhysicalColumnHypothesisReconstructionContextFingerprintVersion:c.reconstructionContextFingerprintVersion,sourcePhysicalColumnHypothesisReconstructionContextFingerprint:c.reconstructionContextFingerprint,status,groups,technicalProblems,metrics,limitations:LIMITATIONS};}

export function formBudgetDocumentPhysicalCellHypotheses(input:BudgetDocumentPhysicalCellHypothesisFormationInput):BudgetDocumentPhysicalCellHypothesisFormationResult {const identity=computeIdentityFingerprint(input);const s=input.structureReconstruction,t=input.tabularRegionDetection,c=input.physicalColumnHypothesisReconstruction;try{
  if(findCompatibleStructureReconstructionContract(s)===null||findCompatibleTabularRegionDetectionContract(t)===null||c.schemaVersion!==1||c.reconstructorName!=="budget-document-physical-column-hypothesis-reconstructor"||c.reconstructorVersion!=="budget-document-physical-column-hypothesis-reconstructor-v1"||c.reconstructionProfileId!==BUDGET_DOCUMENT_PHYSICAL_COLUMN_HYPOTHESIS_RECONSTRUCTION_PROFILE_V1.profileId||c.reconstructionProfileVersion!==1)return buildResult(input,identity,[],[problem("source_contract_version_unsupported","source_validation")],"failed");
  if(s.status==="failed"||t.status==="failed"||c.status==="failed")return buildResult(input,identity,[],[problem(s.status==="failed"?"source_structure_reconstruction_contract_invalid":t.status==="failed"?"source_tabular_region_detection_contract_invalid":"source_physical_column_hypothesis_contract_invalid","source_validation")],"failed");
  if(s.sourceByteHash!==t.sourceByteHash||s.sourceByteHash!==c.sourceByteHash||t.sourceReconstructionContextFingerprint!==s.reconstructionContextFingerprint||c.sourceStructureReconstructionContextFingerprint!==s.reconstructionContextFingerprint||c.sourceTabularRegionDetectionContextFingerprint!==t.detectionContextFingerprint)return buildResult(input,identity,[],[problem("source_lineage_mismatch","source_validation")],"failed");
  const sf=computeStructureReconstructionContextFingerprint({sourceByteHash:s.sourceByteHash,physicalReadSchemaVersion:s.physicalReadSchemaVersion,physicalReaderName:s.physicalReaderName,physicalReaderVersion:s.physicalReaderVersion,physicalAdapterVersion:s.physicalAdapterVersion,physicalUnderlyingLibraryVersion:s.physicalUnderlyingLibraryVersion,textItemCoordinateSpaceVersion:s.physicalTextItemCoordinateSpaceVersion,textItemGeometryProfileVersion:s.physicalTextItemGeometryProfileVersion,geometryContextFingerprintVersion:s.physicalGeometryContextFingerprintVersion,geometryContextFingerprint:s.physicalGeometryContextFingerprint,pageLocationSchemaVersion:s.pageLocationSchemaVersion,pageLocatorName:s.pageLocatorName,pageLocatorVersion:s.pageLocatorVersion,pageLocationDecisionRuleSetVersion:s.pageLocationDecisionRuleSetVersion,sourceObservationSchemaVersion:s.sourceObservationSchemaVersion,sourceObserverName:s.sourceObserverName,pageLocationCatalogVersion:s.sourceCatalogVersion,pageLocationObserverVersion:s.sourceObserverVersion,pageLocationObservationRuleSetVersion:s.sourceObservationRuleSetVersion,reconstructorName:s.reconstructorName,reconstructorVersion:s.reconstructorVersion,profileId:s.reconstructionProfileId,profileVersion:s.reconstructionProfileVersion,geometryCanonicalizationVersion:"structure-reconstruction-output-geometry-canonicalization-v1"});if(sf!==s.reconstructionContextFingerprint)return buildResult(input,identity,[],[problem("source_fingerprint_invalid","source_validation")],"failed");
  const ti=computeTabularRegionDetectionIdentityFingerprint(buildTabularRegionDetectionIdentityFingerprintInput(s,t.detectorName,t.detectorVersion,t.detectionProfileId,t.detectionProfileVersion,VERTICAL_ALIGNMENT_OBSERVATION_RULE_ID,VERTICAL_ALIGNMENT_OBSERVATION_RULE_VERSION,TABULAR_REGION_FORMATION_RULE_ID,TABULAR_REGION_FORMATION_RULE_VERSION,BUDGET_DOCUMENT_TABULAR_REGION_DETECTION_PROFILE_V1.geometryCanonicalizationVersion)); if(computeTabularRegionDetectionContentFingerprint(ti,t.groups)!==t.detectionContextFingerprint)return buildResult(input,identity,[],[problem("source_fingerprint_invalid","source_validation")],"failed");
  const ci=computePhysicalColumnHypothesisReconstructionIdentityFingerprint(buildPhysicalColumnHypothesisReconstructionIdentityFingerprintInput(s,t,c.reconstructorName,c.reconstructorVersion,c.reconstructionProfileId,c.reconstructionProfileVersion,PHYSICAL_VERTICAL_BAND_CONSTRUCTION_RULE_ID,PHYSICAL_VERTICAL_BAND_CONSTRUCTION_RULE_VERSION,COLUMN_RULE_ID,COLUMN_RULE_VERSION,BUDGET_DOCUMENT_PHYSICAL_COLUMN_HYPOTHESIS_RECONSTRUCTION_PROFILE_V1.geometryCanonicalizationVersion)); if(computePhysicalColumnHypothesisReconstructionContentFingerprint(ci,c.groups)!==c.reconstructionContextFingerprint)return buildResult(input,identity,[],[problem("source_fingerprint_invalid","source_validation")],"failed");
  const sGroups=new Map(s.groups.map(x=>[x.sourceCandidateGroupKey,x])); const cGroups=[...c.groups].sort((a,b)=>(sGroups.get(a.sourceCandidateGroupKey)?.startPageNumber??0)-(sGroups.get(b.sourceCandidateGroupKey)?.startPageNumber??0)||a.sourceCandidateGroupKey.localeCompare(b.sourceCandidateGroupKey)); const groups:PhysicalCellHypothesisFormationGroup[]=cGroups.map(cg=>{const sg=sGroups.get(cg.sourceCandidateGroupKey);const groupKey=computeGroupProcessedKey(identity,cg.sourceCandidateGroupKey);if(!sg)return {groupProcessedKey:groupKey,sourceCandidateGroupKey:cg.sourceCandidateGroupKey,status:"group_not_processable",pageKeys:[],pages:[],technicalProblems:[problem("source_group_reference_invalid","candidate_group_processing",{groupKey:cg.sourceCandidateGroupKey})],metrics:groupMetrics([])};const pageByNumber=new Map(sg.pages.map(x=>[x.pageNumber,x]));const pages:PhysicalCellHypothesisFormationPage[]=[...cg.pages].sort((a,b)=>a.pageNumber-b.pageNumber).map(cp=>{const pageKey=computePageProcessedKey(groupKey,cp.pageNumber);const sp=pageByNumber.get(cp.pageNumber);if(!sp)return {pageProcessedKey:pageKey,pageNumber:cp.pageNumber,status:"page_not_processable",regions:[],technicalProblems:[problem("source_page_reference_invalid","candidate_page_processing",{groupKey:cg.sourceCandidateGroupKey,pageNumber:cp.pageNumber})],metrics:pageMetrics([])};const regions=cp.regions.map(r=>processRegion(r,sp,computeRegionProcessedKey(pageKey,r.sourceRegionKey)));const pm=pageMetrics(regions);const status=regions.length>0&&regions.every(x=>x.status==="region_not_processable")?"page_not_processable":regions.some(x=>x.status==="formed_with_problems"||x.status==="region_not_processable")?"formed_with_problems":regions.some(x=>x.status==="formed_with_ambiguities")?"formed_with_ambiguities":regions.length===0||regions.every(x=>x.status==="no_physical_grid")?"no_physical_grid":"formed";return {pageProcessedKey:pageKey,pageNumber:cp.pageNumber,status,regions,technicalProblems:[],metrics:pm};});const gm=groupMetrics(pages);const status=pages.length>0&&pages.every(x=>x.status==="page_not_processable")?"group_not_processable":pages.some(x=>x.status==="formed_with_problems"||x.status==="page_not_processable")?"formed_with_problems":pages.some(x=>x.status==="formed_with_ambiguities")?"formed_with_ambiguities":pages.length===0||pages.every(x=>x.status==="no_physical_grid")?"no_physical_grid":"formed";return {groupProcessedKey:groupKey,sourceCandidateGroupKey:cg.sourceCandidateGroupKey,status,pageKeys:pages.map(x=>x.pageProcessedKey),pages,technicalProblems:[],metrics:gm};});const status=groups.some(x=>x.status==="formed_with_problems"||x.status==="group_not_processable")?"completed_with_problems":groups.some(x=>x.status==="formed_with_ambiguities")?"completed_with_ambiguities":"completed";return buildResult(input,identity,groups,[],status);
 }catch{return buildResult(input,identity,[],[problem("physical_cell_hypothesis_formation_unexpected_failure","candidate_group_processing")],"failed");}}
