import { buildPhysicalColumnHypothesisReconstructionFixture, type SyntheticGeometryPage, type SyntheticGeometryTextItem } from "../physical-column-hypothesis-reconstruction/testing/physical-column-hypothesis-reconstruction-test-bridge";
import { reconstructBudgetDocumentPhysicalColumnHypotheses } from "../physical-column-hypothesis-reconstruction";
import { formBudgetDocumentPhysicalCellHypotheses } from "./form-budget-document-physical-cell-hypotheses";

function runTest(name:string,fn:()=>void):void{fn();console.log(`ok - ${name}`);}
function equal(a:unknown,b:unknown,m="values differ"):void{if(a!==b)throw new Error(`${m}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);}
const rows=(count=4):ReadonlyArray<SyntheticGeometryTextItem>=>Array.from({length:count},(_,row)=>{const top=700-row*25;return [{text:`a-${row}`,leftPoints:100,topPoints:top,rightPoints:160,bottomPoints:top+12,index:row*2},{text:`b-${row}`,leftPoints:300,topPoints:top,rightPoints:360,bottomPoints:top+12,index:row*2+1}]}).flat();
const page=(items:ReadonlyArray<SyntheticGeometryTextItem>):SyntheticGeometryPage=>({widthPoints:612,heightPoints:792,items});
function input(items=rows()){const upstream=buildPhysicalColumnHypothesisReconstructionFixture("cell-formation",[page(items)]);return {...upstream,physicalColumnHypothesisReconstruction:reconstructBudgetDocumentPhysicalColumnHypotheses(upstream)};}

runTest("forms the complete line-by-column product and one cell per populated intersection",()=>{const result=formBudgetDocumentPhysicalCellHypotheses(input());equal(result.status,"completed");const region=result.groups[0].pages[0].regions[0];equal(region.metrics.sourceLineCount,4);equal(region.metrics.sourcePhysicalColumnHypothesisCount,2);equal(region.gridIntersections.length,8);equal(region.cellHypotheses.length,8);equal(region.segmentDispositions.every(x=>x.status==="included_in_physical_cell_hypothesis"),true);});
runTest("cell and intersection do not duplicate structural identity or segment ownership",()=>{const region=formBudgetDocumentPhysicalCellHypotheses(input()).groups[0].pages[0].regions[0];const intersection=region.gridIntersections[0];const cell=region.cellHypotheses.find(x=>x.gridIntersectionKey===intersection.gridIntersectionKey)!;equal("segmentKeys" in intersection,false);equal("gridBounds" in cell,false);equal("sourceLineKey" in cell,false);equal(cell.segmentKeys.length,1);});
runTest("is deterministic",()=>{const source=input();equal(JSON.stringify(formBudgetDocumentPhysicalCellHypotheses(source)),JSON.stringify(formBudgetDocumentPhysicalCellHypotheses(source)));});
runTest("preserves empty positions for a column absent from one participating line",()=>{const items:SyntheticGeometryTextItem[]=[];for(let row=0;row<4;row++){const top=700-row*25;items.push({text:`clean-${row}`,leftPoints:300,topPoints:top,rightPoints:360,bottomPoints:top+12,index:row});if(row<3)items.push({text:`partial-${row}`,leftPoints:100,topPoints:top,rightPoints:160,bottomPoints:top+12,index:4+row});}const result=formBudgetDocumentPhysicalCellHypotheses(input(items));const region=result.groups[0].pages[0].regions[0];equal(region.gridIntersections.some(x=>x.status==="empty"),true);equal(region.metrics.totalGridIntersectionCount,region.metrics.sourceLineCount*region.metrics.sourcePhysicalColumnHypothesisCount);});
runTest("does not read or depend on textual content in production",()=>{const source=input();const changed={...source,structureReconstruction:source.structureReconstruction};const a=formBudgetDocumentPhysicalCellHypotheses(source);const b=formBudgetDocumentPhysicalCellHypotheses(changed);equal(JSON.stringify(a),JSON.stringify(b));});
