import type { GlobalPhysicalCellHypothesisFormationMetrics, GroupPhysicalCellHypothesisFormationMetrics, PagePhysicalCellHypothesisFormationMetrics, PhysicalCellHypothesis, PhysicalCellHypothesisFormationGroup, PhysicalCellHypothesisFormationPage, PhysicalCellHypothesisFormationRegion, PhysicalCellHypothesisSegmentDisposition, PhysicalGridIntersection, RegionPhysicalCellHypothesisFormationMetrics } from "./budget-document-physical-cell-hypothesis-formation.types";

export function computeRegionMetrics(intersections: ReadonlyArray<PhysicalGridIntersection>, cells: ReadonlyArray<PhysicalCellHypothesis>, dispositions: ReadonlyArray<PhysicalCellHypothesisSegmentDisposition>, lineCount: number, columnCount: number, problemCount: number): RegionPhysicalCellHypothesisFormationMetrics {
  return {
    sourceLineCount: lineCount, sourcePhysicalColumnHypothesisCount: columnCount, totalGridIntersectionCount: intersections.length,
    cellHypothesisFormedIntersectionCount: intersections.filter((entry) => entry.status === "cell_hypothesis_formed").length,
    emptyGridIntersectionCount: intersections.filter((entry) => entry.status === "empty").length,
    ambiguousGridIntersectionCount: intersections.filter((entry) => entry.status === "unresolved_segment_association_ambiguity").length,
    formationFailedGridIntersectionCount: intersections.filter((entry) => entry.status === "unresolved_technical_failure").length,
    totalRegionSegmentCount: dispositions.length,
    includedSegmentCount: dispositions.filter((entry) => entry.status === "included_in_physical_cell_hypothesis").length,
    outsideSegmentCount: dispositions.filter((entry) => entry.status === "outside_all_physical_cell_hypotheses").length,
    inheritedAmbiguousSegmentCount: dispositions.filter((entry) => entry.status === "unresolved_inherited_column_ambiguity").length,
    partialIntersectionSegmentCount: dispositions.filter((entry) => entry.status === "unresolved_partial_grid_intersection").length,
    multipleClaimSegmentCount: dispositions.filter((entry) => entry.status === "unresolved_multiple_grid_intersection_claim").length,
    sourceContractInconsistentSegmentCount: dispositions.filter((entry) => entry.status === "unresolved_source_contract_inconsistency").length,
    formationFailedSegmentCount: dispositions.filter((entry) => entry.status === "unresolved_cell_hypothesis_formation_failed").length,
    cellHypothesisCount: cells.length, multiSegmentCellHypothesisCount: cells.filter((entry) => entry.segmentKeys.length > 1).length, technicalProblemCount: problemCount,
  };
}

export function computePageMetrics(regions: ReadonlyArray<PhysicalCellHypothesisFormationRegion>): PagePhysicalCellHypothesisFormationMetrics {
  const metrics = regions.map((entry) => entry.metrics);
  return { totalRegionCount: regions.length, formedRegionCount: regions.filter((entry) => entry.status === "formed").length, formedWithAmbiguitiesRegionCount: regions.filter((entry) => entry.status === "formed_with_ambiguities").length, formedWithProblemsRegionCount: regions.filter((entry) => entry.status === "formed_with_problems").length, gridWithoutCellHypothesesRegionCount: regions.filter((entry) => entry.status === "grid_without_cell_hypotheses").length, noPhysicalGridRegionCount: regions.filter((entry) => entry.status === "no_physical_grid").length, regionNotProcessableCount: regions.filter((entry) => entry.status === "region_not_processable").length, gridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.totalGridIntersectionCount, 0), emptyGridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.emptyGridIntersectionCount, 0), cellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.cellHypothesisCount, 0), multiSegmentCellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.multiSegmentCellHypothesisCount, 0), segmentCount: metrics.reduce((sum, entry) => sum + entry.totalRegionSegmentCount, 0), includedSegmentCount: metrics.reduce((sum, entry) => sum + entry.includedSegmentCount, 0), ambiguousSegmentCount: metrics.reduce((sum, entry) => sum + entry.inheritedAmbiguousSegmentCount + entry.partialIntersectionSegmentCount + entry.multipleClaimSegmentCount, 0), formationFailedSegmentCount: metrics.reduce((sum, entry) => sum + entry.formationFailedSegmentCount, 0), technicalProblemCount: metrics.reduce((sum, entry) => sum + entry.technicalProblemCount, 0) };
}

export function computeGroupMetrics(pages: ReadonlyArray<PhysicalCellHypothesisFormationPage>): GroupPhysicalCellHypothesisFormationMetrics {
  const metrics = pages.map((entry) => entry.metrics);
  return { totalPageCount: pages.length, formedPageCount: pages.filter((entry) => entry.status === "formed").length, formedWithAmbiguitiesPageCount: pages.filter((entry) => entry.status === "formed_with_ambiguities").length, formedWithProblemsPageCount: pages.filter((entry) => entry.status === "formed_with_problems").length, noPhysicalGridPageCount: pages.filter((entry) => entry.status === "no_physical_grid").length, pageNotProcessableCount: pages.filter((entry) => entry.status === "page_not_processable").length, gridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.gridIntersectionCount, 0), emptyGridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.emptyGridIntersectionCount, 0), cellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.cellHypothesisCount, 0), multiSegmentCellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.multiSegmentCellHypothesisCount, 0), segmentCount: metrics.reduce((sum, entry) => sum + entry.segmentCount, 0), includedSegmentCount: metrics.reduce((sum, entry) => sum + entry.includedSegmentCount, 0), ambiguousSegmentCount: metrics.reduce((sum, entry) => sum + entry.ambiguousSegmentCount, 0), formationFailedSegmentCount: metrics.reduce((sum, entry) => sum + entry.formationFailedSegmentCount, 0), technicalProblemCount: metrics.reduce((sum, entry) => sum + entry.technicalProblemCount, 0) };
}

export function computeGlobalMetrics(groups: ReadonlyArray<PhysicalCellHypothesisFormationGroup>): GlobalPhysicalCellHypothesisFormationMetrics {
  const metrics = groups.map((entry) => entry.metrics);
  return { receivedGroupCount: groups.length, formedGroupCount: groups.filter((entry) => entry.status === "formed").length, formedWithAmbiguitiesGroupCount: groups.filter((entry) => entry.status === "formed_with_ambiguities").length, formedWithProblemsGroupCount: groups.filter((entry) => entry.status === "formed_with_problems").length, noPhysicalGridGroupCount: groups.filter((entry) => entry.status === "no_physical_grid").length, groupNotProcessableCount: groups.filter((entry) => entry.status === "group_not_processable").length, candidatePageCount: metrics.reduce((sum, entry) => sum + entry.totalPageCount, 0), candidateRegionCount: groups.reduce((sum, group) => sum + group.pages.reduce((pageSum, page) => pageSum + page.metrics.totalRegionCount, 0), 0), gridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.gridIntersectionCount, 0), emptyGridIntersectionCount: metrics.reduce((sum, entry) => sum + entry.emptyGridIntersectionCount, 0), cellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.cellHypothesisCount, 0), multiSegmentCellHypothesisCount: metrics.reduce((sum, entry) => sum + entry.multiSegmentCellHypothesisCount, 0), segmentCount: metrics.reduce((sum, entry) => sum + entry.segmentCount, 0), includedSegmentCount: metrics.reduce((sum, entry) => sum + entry.includedSegmentCount, 0), ambiguousSegmentCount: metrics.reduce((sum, entry) => sum + entry.ambiguousSegmentCount, 0), formationFailedSegmentCount: metrics.reduce((sum, entry) => sum + entry.formationFailedSegmentCount, 0), technicalProblemCount: metrics.reduce((sum, entry) => sum + entry.technicalProblemCount, 0) };
}
