import { readFileSync,readdirSync,statSync } from "node:fs";
import { dirname,join,relative,resolve } from "node:path";
import { fileURLToPath } from "node:url";
const CURRENT=dirname(fileURLToPath(import.meta.url));const SRC=resolve(CURRENT,"..");const ENGINE=join(SRC,"domain","budget-table-reconstruction");const LOCATION=join(SRC,"domain","budget-document-location");
const SKIP=new Set(["testing","fixtures","discovery","reference-truth","cell-geometry","expected-cell-geometry","local-reader-evaluation","results","ground-truth","evaluation-output","expected-cells"]);
function files(root:string):string[]{const output:string[]=[];for(const entry of readdirSync(root)){if(SKIP.has(entry))continue;const path=join(root,entry);if(statSync(path).isDirectory())output.push(...files(path));else if(path.endsWith(".ts")&&!path.endsWith(".test.ts"))output.push(path)}return output.sort()}
function imports(content:string):string[]{return[...content.matchAll(/(?:import|export)\s+(?:type\s+)?(?:[^"']*?\s+from\s+)?["']([^"']+)["']/g)].map(match=>match[1]!)}
function test(name:string,body:()=>void):void{body();console.log(`ok - ${name}`)}function empty(values:ReadonlyArray<string>):void{if(values.length)throw new Error(values.join("\n"))}
const forbiddenPaths=["testing","fixtures","discovery","reference-truth","cell-geometry","expected-cell-geometry","local-reader-evaluation","results","docling","paddleocr","openai","anthropic","supabase","apps/web","pdfjs-dist","infrastructure","budget-version","document-reconstruction","procurement-engineering","persistence"];
test("engine imports only its upstream physical domain and node crypto",()=>{const violations:string[]=[];for(const file of files(ENGINE)){for(const specifier of imports(readFileSync(file,"utf8"))){const normalized=specifier.toLowerCase();if(forbiddenPaths.some(value=>normalized.includes(value)))violations.push(`${relative(SRC,file)} imports ${specifier}`)}}empty(violations)});
test("budget document location never imports the semantic engine",()=>{const violations=files(LOCATION).filter(file=>imports(readFileSync(file,"utf8")).some(specifier=>specifier.includes("budget-table-reconstruction"))).map(file=>relative(SRC,file));empty(violations)});
test("productive engine has no case-specific literals or page conditionals",()=>{const patterns=[/lagoa\s+do\s+arroz/i,/05_anexo_tecnico/i,/\b(?:page|pagenumber)\s*={2,3}\s*(?:46|50|54)\b/i,/\b(?:46|50|54)\s*={2,3}\s*(?:page|pagenumber)\b/i,/Date\.now\s*\(/,/Math\.random\s*\(/,/randomUUID\s*\(/,/Math\.round\s*\(/,/\.toFixed\s*\(/,/parseFloat\s*\(/];const violations:string[]=[];for(const file of files(ENGINE)){const content=readFileSync(file,"utf8");for(const pattern of patterns)if(pattern.test(content))violations.push(`${relative(SRC,file)} matches ${pattern}`)}empty(violations)});
test("productive barrels never export diagnostic paths",()=>{const violations=files(ENGINE).filter(file=>file.endsWith("index.ts")).flatMap(file=>imports(readFileSync(file,"utf8")).filter(specifier=>forbiddenPaths.slice(0,8).some(value=>specifier.toLowerCase().includes(value))).map(specifier=>`${relative(SRC,file)} exports ${specifier}`));empty(violations)});
