import { pdfjsPhysicalDocumentReader } from "./pdfjs-physical-document-reader";
import { buildSyntheticPdfBytes } from "./testing/synthetic-pdf-bytes";
import { observeDocumentSignals, locateBudgetDocumentPages, reconstructBudgetDocumentStructure, detectBudgetDocumentTabularRegions, reconstructBudgetDocumentPhysicalColumnHypotheses, formBudgetDocumentPhysicalCellHypotheses } from "../../../domain/budget-document-location";

function equal(a:unknown,b:unknown,m="values differ"):void{if(a!==b)throw new Error(`${m}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);}
const bytes=buildSyntheticPdfBytes([{items:[0,1,2,3].flatMap(row=>{const y=700-row*34;return [{text:`1.${row+1} Servico ${row}`,x:72,y,fontSize:18},{text:`${row+1}0,00`,x:400,y,fontSize:18},...(row===0?[{text:"BDI",x:500,y,fontSize:18}]:[])];})}]);
async function chain(){const physicalRead=await pdfjsPhysicalDocumentReader.read(bytes.slice());const observation=observeDocumentSignals(physicalRead);const pageLocation=locateBudgetDocumentPages(observation);const structureReconstruction=reconstructBudgetDocumentStructure({physicalRead,pageLocation});const tabularRegionDetection=detectBudgetDocumentTabularRegions({structureReconstruction});const physicalColumnHypothesisReconstruction=reconstructBudgetDocumentPhysicalColumnHypotheses({structureReconstruction,tabularRegionDetection});return formBudgetDocumentPhysicalCellHypotheses({structureReconstruction,tabularRegionDetection,physicalColumnHypothesisReconstruction});}
async function main(){const a=await chain();equal(a.status,"completed");equal(a.groups.length,1);const region=a.groups[0].pages[0].regions[0];equal(region.gridIntersections.length,8);equal(region.cellHypotheses.length,8);equal(region.segmentDispositions.filter(x=>x.status==="outside_all_physical_cell_hypotheses").length,1,"BDI remains an orphan");const b=await chain();equal(JSON.stringify(a),JSON.stringify(b),"real PDF chain must be deterministic");console.log("ok - synthetic PDF bytes traverse the complete real chain through physical cell hypotheses");}
main().catch(e=>{console.error(e);process.exit(1);});
