import { fingerprintCanonical } from "./budget-table-reconstruction-fingerprint";
import { parseNumericEvidence } from "./budget-table-reconstruction-numeric-evidence";
import type { BudgetColumnRole,ParsedNumericEvidence,ReconstructedBudgetRecord,ReconstructedLogicalRow,ReconstructedRecordKind } from "./budget-table-reconstruction.types";
function text(row:ReconstructedLogicalRow,role:BudgetColumnRole):string|null{return row.cells.filter(cell=>cell.role===role).map(cell=>cell.rawText).filter((v):v is string=>v!==null).join(" ").trim()||null}
function numeric(row:ReconstructedLogicalRow,role:BudgetColumnRole):ParsedNumericEvidence|null{const cells=row.cells.filter(cell=>cell.role===role);const raw=cells.map(cell=>cell.rawText).filter((v):v is string=>v!==null).join(" ").trim();if(!raw)return null;return parseNumericEvidence(raw,cells.flatMap(cell=>cell.fragments))}
export function classifyRecords(rows:ReadonlyArray<ReconstructedLogicalRow>):ReadonlyArray<ReconstructedBudgetRecord>{const records:ReconstructedBudgetRecord[]=[];const depths=new Set(rows.map(row=>text(row,"item_code")).filter((v):v is string=>v!==null).filter(code=>/^\d+(?:\.\d+)+$/.test(code)).map(code=>code.split(".").length));
 for(const row of rows){if(row.kind==="header"||row.kind==="description_continuation")continue;let kind:ReconstructedRecordKind=row.kind==="group"?"unclassified":row.kind;const code=text(row,"item_code");if(row.kind==="group"&&code&&/^\d+(?:\.\d+)*$/.test(code)){const depth=code.split(".").length;kind=depths.has(depth+1)?(depth===Math.min(...depths)?"group":"subgroup"):"unclassified"}
  const continuation=rows.filter(candidate=>candidate.kind==="description_continuation"&&candidate.descriptionSourceRowIds.includes(row.rowId));const description=[row.description,...continuation.map(value=>value.description)].filter((v):v is string=>v!==null).join(" ")||null;const recordId=`record:${fingerprintCanonical({rowLocator:row.locator,kind})}`;
  const prefix=code&&code.includes(".")?code.slice(0,code.lastIndexOf(".")):null;const parent=prefix?[...records].reverse().find(record=>record.itemCode===prefix&&(record.kind==="group"||record.kind==="subgroup")):undefined;
  records.push({recordId,kind,status:kind==="unclassified"?"insufficient_evidence":row.status,rowIds:[row.rowId,...continuation.map(value=>value.rowId)],parentRecordId:parent?.recordId??null,itemCode:code,description,unit:text(row,"unit"),quantity:numeric(row,"quantity"),unitCost:numeric(row,"unit_cost"),bdiRate:numeric(row,"bdi_rate"),unitPrice:numeric(row,"unit_price"),totalPrice:numeric(row,"total_price")});
 } return records;
}
