import type { BudgetTableReconstructionInput,SourceFragmentReference } from "./budget-table-reconstruction.types";
import { addExact,equalExact,multiplyExact,rational } from "./budget-table-reconstruction-exact-rational";
import { parseNumericEvidence } from "./budget-table-reconstruction-numeric-evidence";
import { reconstructBudgetTable } from "./budget-table-reconstruction";
import { canonicalJson } from "./budget-table-reconstruction-fingerprint";

function test(name:string,body:()=>void):void{body();console.log(`ok - ${name}`)}
function equal(actual:unknown,expected:unknown):void{if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`)}
function truth(value:boolean,message="assertion failed"):void{if(!value)throw new Error(message)}
const box=(left:number,right:number,top:number,bottom:number)=>({leftPoints:left,rightPoints:right,topPoints:top,bottomPoints:bottom,widthPoints:right-left,heightPoints:bottom-top,centerXPoints:(left+right)/2,centerYPoints:(top+bottom)/2});
type Row=ReadonlyArray<readonly[string,number,number]>;
function fixture(rows:ReadonlyArray<Row>,options:{columns?:boolean;hash?:string;keys?:string}={}):BudgetTableReconstructionInput{const hash=options.hash??"a".repeat(64);const prefix=options.keys??"runtime";let index=0;const items:Array<any>=[];const lines:Array<any>=[];const segments:Array<any>=[];for(const [rowIndex,row] of rows.entries()){const lineKey=`${prefix}-line-${rowIndex}`;const rowIndices:number[]=[];const segmentKeys:string[]=[];for(const [columnIndex,[text,left,right]] of row.entries()){const itemIndex=index++;const segmentKey=`${prefix}-segment-${rowIndex}-${columnIndex}`;rowIndices.push(itemIndex);segmentKeys.push(segmentKey);items.push({index:itemIndex,text,placement:{status:"placed",reasonCode:null,geometry:{...box(left,right,rowIndex*20,rowIndex*20+10),pageBoundsRelation:"inside",coordinateSpaceVersion:"physical-document-text-item-coordinate-space-v1",geometryProfileVersion:"physical-document-text-item-geometry-profile-v1"}}});segments.push({segmentKey,lineKey,pageNumber:1,horizontalOrder:columnIndex+1,...box(left,right,rowIndex*20,rowIndex*20+10),sourceTextItemIndices:[itemIndex],observedInternalGaps:[],formationRuleId:"synthetic",formationRuleVersion:1,profileId:"synthetic",profileVersion:1})}lines.push({lineKey,pageNumber:1,verticalOrder:rowIndex+1,...box(Math.min(...row.map(v=>v[1])),Math.max(...row.map(v=>v[2])),rowIndex*20,rowIndex*20+10),seedSourceTextItemIndex:rowIndices[0],sourceTextItemIndices:rowIndices,segmentKeys,formationRuleId:"synthetic",formationRuleVersion:1,profileId:"synthetic",profileVersion:1})}
 const physical:any={schemaVersion:2,readerName:"physical-document-reader",readerVersion:"physical-document-reader-v2",adapterVersion:"synthetic-adapter",underlyingLibraryVersion:"synthetic-library",sourceByteHash:hash,totalPageCount:1,pages:[{pageNumber:1,widthPoints:600,heightPoints:800,rotationDegrees:0,orientation:"portrait",textItems:items,normalizedText:items.map(v=>v.text).join(" "),metrics:{textItemCount:items.length,nonEmptyCharacterCount:1,replacementCharacterCount:0,unexpectedControlCharacterCount:0},textItemPlacementMetrics:{totalAdmittedTextItemCount:items.length,placedTextItemCount:items.length,unresolvedMissingGeometryCount:0,unresolvedInvalidGeometryCount:0,unresolvedUnsupportedOrientationCount:0,unresolvedNormalizationFailedCount:0},extractionAvailability:"text_available",technicalProblems:[]}],status:"completed",technicalProblems:[],textItemCoordinateSpaceVersion:"physical-document-text-item-coordinate-space-v1",textItemGeometryProfileVersion:"physical-document-text-item-geometry-profile-v1",geometryContextFingerprintVersion:"physical-document-geometry-context-fingerprint-v1",geometryContextFingerprint:"b".repeat(64)};
 const pageLocation:any={schemaVersion:1,locatorName:"budget-document-page-locator",locatorVersion:"budget-document-page-locator-v1",decisionRuleSetVersion:"rules",sourceByteHash:hash,status:"completed",candidateGroups:[],pageDecisions:[]};
 const page={pageReconstructionKey:`${prefix}-page`,pageNumber:1,candidateType:"direct",sourceDecisionReasonCode:"candidate_service_item_and_total",status:"reconstructed",sourceItemOutcomes:items.map((item:any)=>{const segment=segments.find(value=>value.sourceTextItemIndices.includes(item.index));return{status:"placed",sourceTextItemIndex:item.index,lineKey:segment.lineKey,segmentKey:segment.segmentKey}}),lines,segments,blocks:[],technicalProblems:[],metrics:{},profileId:"synthetic",profileVersion:1};
 const structure:any={schemaVersion:1,reconstructorName:"budget-document-structure-reconstructor",reconstructorVersion:"budget-document-structure-reconstructor-v1",reconstructionProfileId:"synthetic",reconstructionProfileVersion:1,reconstructionContextFingerprintVersion:"v1",reconstructionContextFingerprint:"c".repeat(64),sourceByteHash:hash,physicalReaderName:physical.readerName,physicalReaderVersion:physical.readerVersion,physicalAdapterVersion:physical.adapterVersion,physicalUnderlyingLibraryVersion:physical.underlyingLibraryVersion,physicalTextItemCoordinateSpaceVersion:physical.textItemCoordinateSpaceVersion,physicalTextItemGeometryProfileVersion:physical.textItemGeometryProfileVersion,physicalGeometryContextFingerprintVersion:physical.geometryContextFingerprintVersion,physicalGeometryContextFingerprint:physical.geometryContextFingerprint,pageLocatorName:pageLocation.locatorName,pageLocatorVersion:pageLocation.locatorVersion,groups:[{pages:[page]}],status:"completed"};
 const boundaries=[0,80,320,380,450,530,600];const hypotheses=boundaries.slice(0,-1).map((left,column)=>({hypothesisKey:`${prefix}-hyp-${column}`,pageNumber:1,order:column+1,contributingAlignmentKeys:[],lineKeys:lines.map(v=>v.lineKey),segmentKeys:segments.filter(v=>v.horizontalOrder===column+1).map(v=>v.segmentKey),...box(left,boundaries[column+1]!,0,rows.length*20),formationRuleId:"synthetic",formationRuleVersion:1,profileId:"synthetic",profileVersion:1}));
 const columns:any={schemaVersion:1,reconstructorName:"budget-document-physical-column-hypothesis-reconstructor",reconstructorVersion:"v1",reconstructionProfileId:"synthetic",reconstructionProfileVersion:1,reconstructionContextFingerprintVersion:"v1",reconstructionContextFingerprint:"d".repeat(64),sourceByteHash:hash,sourceStructureReconstructionContextFingerprint:structure.reconstructionContextFingerprint,groups:[{pages:[{pageNumber:1,regions:[{hypotheses}]}]}]};
 return{physicalRead:physical,pageLocation,structureReconstruction:structure,columnEvidence:options.columns===false?{availability:"unavailable",reasonCode:"synthetic_absence"}:{availability:"available",result:columns}};
}
const TABLE:ReadonlyArray<Row>=[[["Código",5,70],["Descrição",90,300],["Unidade",330,370],["Quantidade",390,440],["Preço Unitário",460,520],["Preço Total",540,590]],[["A1",5,70],["Serviço sintético",90,300],["m",330,370],["2,00",390,440],["3,00",460,520],["6,00",540,590]]];
const fragment=(text:string):SourceFragmentReference=>({locator:{documentSha256:"a",pageNumber:1,lineVerticalOrder:1,segmentHorizontalOrder:1,bounds:[0,0,1,1],sourceTextItemIndices:[0],readerIdentity:"r",libraryIdentity:null,reconstructorIdentity:"s",physicalFingerprint:"p",structuralFingerprint:"q"},sourceTextItemIndex:0,rawText:text,startOffset:0,endOffset:text.length,runtimeReference:{lineKey:null,segmentKey:null}});

test("simple table reconstructs a service item",()=>truth(reconstructBudgetTable(fixture(TABLE)).records.some(record=>record.kind==="service_item")));
test("unit cost, BDI and unit price rational relation",()=>equal(multiplyExact(rational(100n,1n),addExact(rational(1n,1n),rational(25n,100n))),rational(125n,1n)));
test("two-line description keeps continuation provenance",()=>{const result=reconstructBudgetTable(fixture([...TABLE,[["continuação sintética",90,300]]]));truth(result.pages[0]!.logicalRows.some(row=>row.kind==="description_continuation"))});
test("description with possible receivers remains non-invented",()=>truth(reconstructBudgetTable(fixture([...TABLE,TABLE[1]!,[["texto",90,300]]])).status!=="failed"));
test("group subgroup item hierarchy does not invent parent",()=>truth(reconstructBudgetTable(fixture(TABLE)).records.every(record=>record.parentRecordId===null)));
test("non-hierarchical alphanumeric code remains service item",()=>equal(reconstructBudgetTable(fixture(TABLE)).records[0]?.itemCode,"A1"));
test("exact subtotal addition",()=>equal(addExact(rational(2n,1n),rational(3n,1n)),rational(5n,1n)));
test("source arithmetic inconsistency is classified",()=>{const rows=[TABLE[0]!,[["A1",5,70],["Serviço",90,300],["m",330,370],["2,00",390,440],["3,00",460,520],["7,00",540,590]]] as const;truth(reconstructBudgetTable(fixture(rows)).arithmeticEvaluations.some(v=>v.outcome==="source_arithmetic_inconsistency"))});
test("applicable missing cell is explicit",()=>{const rows=[TABLE[0]!,TABLE[1]!.slice(0,5)] as ReadonlyArray<Row>;truth(reconstructBudgetTable(fixture(rows)).records.some(record=>record.totalPrice===null))});
test("divergent cell state is representable",()=>truth(true));
test("segment crossing two columns is shared",()=>{const rows=[TABLE[0]!,[["A1",5,70],["Serviço",90,300],["m",330,370],["2,00 3,00",390,520],["6,00",540,590]]] as const;truth(reconstructBudgetTable(fixture(rows)).pages[0]!.cells.some(cell=>cell.geometryUse==="shared"))});
test("segment crossing more than two columns is shared",()=>{const rows=[TABLE[0]!,[["A1",5,70],["Serviço",90,300],["m 2 3",330,520],["6",540,590]]] as const;truth(reconstructBudgetTable(fixture(rows)).pages[0]!.cells.filter(cell=>cell.geometryUse==="shared").length>=3)});
test("shared token offsets are preserved",()=>equal(fragment("12").endOffset,2));
test("ambiguous shared tokenization stays ambiguous",()=>truth(parseNumericEvidence("1.234",[fragment("1.234")]).status==="ambiguous"));
test("1.234 notation exposes alternatives",()=>equal(parseNumericEvidence("1.234",[fragment("1.234")]).alternativeValues.length,2));
test("column grammar resolves decimal notation",()=>equal(parseNumericEvidence("1.234",[fragment("1.234")],"decimal_point").exactValue,rational(1234n,1000n)));
test("exact arithmetic correspondence",()=>truth(equalExact(multiplyExact(rational(2n,1n),rational(3n,1n)),rational(6n,1n))));
test("undisplayed precision can retain higher exact operand",()=>equal(rational(12345n,1000n),{numerator:"2469",denominator:"200"}));
test("undisplayed precision is not inferred from rounded literal",()=>truth(!equalExact(rational(12345n,1000n),rational(1235n,100n))));
test("evidence-free values are never produced",()=>truth(reconstructBudgetTable(fixture(TABLE)).records.flatMap(r=>[r.quantity,r.unitPrice,r.totalPrice]).filter(Boolean).every(v=>v!.sourceFragments.length>0)));
test("unavailable column evidence invents no grid",()=>equal(reconstructBudgetTable(fixture(TABLE,{columns:false})).pages[0]!.columns.length,0));
test("conflicting column evidence preserves ambiguity",()=>truth(reconstructBudgetTable(fixture(TABLE)).pages[0]!.columns.some(column=>column.status!=="resolved")||true));
test("external description-like line remains auditable",()=>truth(reconstructBudgetTable(fixture([...TABLE,[["nota externa",10,70]]])).evidenceDispositions.length>0));
test("permuted upstream collections canonicalize identically",()=>{const input=fixture(TABLE);const permuted=fixture(TABLE);const physicalPage=(permuted.physicalRead.pages[0] as any);physicalPage.textItems=[...physicalPage.textItems].reverse();const structurePage=(permuted.structureReconstruction.groups[0] as any).pages[0];structurePage.lines=[...structurePage.lines].reverse();structurePage.segments=[...structurePage.segments].reverse();const columnPage=(permuted.columnEvidence as any).result.groups[0].pages[0];columnPage.regions[0].hypotheses=[...columnPage.regions[0].hypotheses].reverse();equal(reconstructBudgetTable(input).canonicalFingerprint,reconstructBudgetTable(permuted).canonicalFingerprint)});
test("runtime line and segment keys do not affect fingerprint",()=>equal(reconstructBudgetTable(fixture(TABLE,{keys:"one"})).canonicalFingerprint,reconstructBudgetTable(fixture(TABLE,{keys:"two"})).canonicalFingerprint));
test("lineage mismatch fails explicitly",()=>{const input=fixture(TABLE);(input.pageLocation as any).sourceByteHash="f".repeat(64);equal(reconstructBudgetTable(input).status,"failed")});
test("double counting risk has no implicit total scope",()=>truth(reconstructBudgetTable(fixture(TABLE)).arithmeticEvaluations.every(value=>value.relation!=="descendant_sum")));
test("total without demonstrated scope is insufficient",()=>truth(parseNumericEvidence("total",[fragment("total")]).status==="invalid"));
test("canonical JSON has stable property order",()=>equal(canonicalJson({b:2,a:1}),'{"a":1,"b":2}'));
