import { locatorKey, structuralLocator } from "./budget-table-reconstruction-structural-locator";
import type { BudgetTableReconstructionInput,EvidenceLine,EvidenceSegment,EvidenceTextItem,ReconstructedBudgetTablePage,RuntimeSourceReference } from "./budget-table-reconstruction.types";
export function buildEvidencePages(input:BudgetTableReconstructionInput):ReadonlyArray<ReconstructedBudgetTablePage>{
 const structuralPages=input.structureReconstruction.groups.flatMap(group=>group.pages).sort((a,b)=>a.pageNumber-b.pageNumber);
 return structuralPages.map(source=>{const physical=input.physicalRead.pages.find(page=>page.pageNumber===source.pageNumber);const outcomes=new Map(source.sourceItemOutcomes.map(outcome=>[outcome.sourceTextItemIndex,outcome]));
  const lines:EvidenceLine[]=source.lines.slice().sort((a,b)=>a.verticalOrder-b.verticalOrder).map(line=>{const locator=structuralLocator(input,source.pageNumber,line.verticalOrder,null,line,line.sourceTextItemIndices);return{locator,runtimeReference:{lineKey:line.lineKey,segmentKey:null},textItemIndices:[...line.sourceTextItemIndices],segmentLocators:source.segments.filter(segment=>segment.lineKey===line.lineKey).sort((a,b)=>a.horizontalOrder-b.horizontalOrder).map(segment=>structuralLocator(input,source.pageNumber,line.verticalOrder,segment.horizontalOrder,segment,segment.sourceTextItemIndices))}});
  const lineOrders=new Map(source.lines.map(line=>[line.lineKey,line.verticalOrder]));
  const segments:EvidenceSegment[]=source.segments.slice().sort((a,b)=>(lineOrders.get(a.lineKey)??0)-(lineOrders.get(b.lineKey)??0)||a.horizontalOrder-b.horizontalOrder).map(segment=>{const locator=structuralLocator(input,source.pageNumber,lineOrders.get(segment.lineKey)??null,segment.horizontalOrder,segment,segment.sourceTextItemIndices);return{locator,runtimeReference:{lineKey:segment.lineKey,segmentKey:segment.segmentKey},textItemIndices:[...segment.sourceTextItemIndices],rawText:segment.sourceTextItemIndices.map(index=>physical?.textItems.find(item=>item.index===index)?.text??"").join("")}});
  const textItems:EvidenceTextItem[]=(physical?.textItems??[]).slice().sort((a,b)=>a.index-b.index).map(item=>{const outcome=outcomes.get(item.index);const line=outcome?.status==="placed"?source.lines.find(value=>value.lineKey===outcome.lineKey):undefined;const segment=outcome?.status==="placed"?source.segments.find(value=>value.segmentKey===outcome.segmentKey):undefined;const runtimeReference:RuntimeSourceReference={lineKey:line?.lineKey??null,segmentKey:segment?.segmentKey??null};const geometry=item.placement.geometry;return{index:item.index,text:item.text,locator:structuralLocator(input,source.pageNumber,line?.verticalOrder??null,segment?.horizontalOrder??null,geometry,item.index===undefined?[]:[item.index]),runtimeReference,upstreamDisposition:outcome?.status??item.placement.status}});
  return{pageNumber:source.pageNumber,sourceStatus:source.status,textItems,lines,segments,columns:[],cells:[],logicalRows:[]};
 }).sort((a,b)=>a.pageNumber-b.pageNumber);
}
export function evidenceId(kind:string,locator:{readonly documentSha256:string;readonly pageNumber:number;readonly lineVerticalOrder:number|null;readonly segmentHorizontalOrder:number|null;readonly bounds:readonly[number,number,number,number]|null;readonly sourceTextItemIndices:ReadonlyArray<number>;readonly readerIdentity:string;readonly libraryIdentity:string|null;readonly reconstructorIdentity:string;readonly physicalFingerprint:string;readonly structuralFingerprint:string}):string{return`${kind}:${locatorKey(locator)}`}
