import { evaluateArithmetic } from "./budget-table-reconstruction-arithmetic";
import { formCells } from "./budget-table-reconstruction-cell-formation";
import { resolveColumns } from "./budget-table-reconstruction-column-resolution";
import { conserveEvidence } from "./budget-table-reconstruction-conservation";
import { buildEvidencePages } from "./budget-table-reconstruction-evidence-graph";
import { exactFraction } from "./budget-table-reconstruction-exact-rational";
import { fingerprintCanonical } from "./budget-table-reconstruction-fingerprint";
import { validateBudgetTableReconstructionInput } from "./budget-table-reconstruction-input-validation";
import { formLogicalRows } from "./budget-table-reconstruction-logical-row-formation";
import { BUDGET_TABLE_RECONSTRUCTION_ENGINE_NAME,BUDGET_TABLE_RECONSTRUCTION_ENGINE_VERSION,BUDGET_TABLE_RECONSTRUCTION_PROFILE } from "./budget-table-reconstruction-profile";
import { classifyRecords } from "./budget-table-reconstruction-record-classification";
import type { BudgetTableReconstructionInput,BudgetTableReconstructionResult,ReconstructionCompleteness,ReconstructionSourceIdentity } from "./budget-table-reconstruction.types";
function identity(input:BudgetTableReconstructionInput):ReconstructionSourceIdentity{return{sourceByteHash:input.physicalRead.sourceByteHash,physicalReaderName:input.physicalRead.readerName,physicalReaderVersion:input.physicalRead.readerVersion,physicalAdapterVersion:input.physicalRead.adapterVersion,underlyingLibraryVersion:input.physicalRead.underlyingLibraryVersion,physicalGeometryContextFingerprint:input.physicalRead.geometryContextFingerprint,pageLocatorName:input.pageLocation.locatorName,pageLocatorVersion:input.pageLocation.locatorVersion,structureReconstructorName:input.structureReconstruction.reconstructorName,structureReconstructorVersion:input.structureReconstruction.reconstructorVersion,structureFingerprint:input.structureReconstruction.reconstructionContextFingerprint,columnFingerprint:input.columnEvidence.availability==="available"?input.columnEvidence.result.reconstructionContextFingerprint:null}}
function completeness(records:BudgetTableReconstructionResult["records"],failed:boolean):ReconstructionCompleteness{const values=records.flatMap(record=>record.kind==="service_item"?[record.quantity,record.unitPrice,record.totalPrice]:record.kind==="subtotal"||record.kind==="total"?[record.totalPrice]:[]);const present=values.filter(value=>value?.status==="resolved").length;const missing=values.filter(value=>value===null).length;const divergent=0;const ambiguous=values.filter(value=>value?.status==="ambiguous").length;const unresolved=records.some(record=>record.status==="insufficient_evidence");return{applicableFieldCount:values.length,presentFieldCount:present,missingFieldCount:missing,divergentFieldCount:divergent,ambiguousFieldCount:ambiguous,exactFraction:exactFraction(present,values.length),status:failed?"failed":unresolved?"insufficient":missing?"partial":ambiguous?"insufficient":"complete"}}
export function reconstructBudgetTable(input:BudgetTableReconstructionInput):BudgetTableReconstructionResult{const validationIssues=validateBudgetTableReconstructionInput(input);const sourceIdentity=identity(input);if(validationIssues.length){const failed={schemaVersion:1 as const,engineName:BUDGET_TABLE_RECONSTRUCTION_ENGINE_NAME,engineVersion:BUDGET_TABLE_RECONSTRUCTION_ENGINE_VERSION,profileId:BUDGET_TABLE_RECONSTRUCTION_PROFILE.profileId,profileVersion:BUDGET_TABLE_RECONSTRUCTION_PROFILE.profileVersion,sourceIdentity,status:"failed" as const,pages:[],records:[],arithmeticEvaluations:[],evidenceDispositions:[],structuralIssues:validationIssues,completeness:completeness([],true),canonicalFingerprint:""};return{...failed,canonicalFingerprint:fingerprintCanonical(failed)}}
 const basePages=buildEvidencePages(input);const columns=resolveColumns(input,basePages);const pages=basePages.map(page=>{const pageColumns=columns.get(page.pageNumber)??[];const withCells={...page,columns:pageColumns,cells:formCells(page,pageColumns)};return{...withCells,logicalRows:formLogicalRows(withCells)}});const rows=pages.flatMap(page=>page.logicalRows);const records=classifyRecords(rows);const arithmeticEvaluations=evaluateArithmetic(records,rows);const conservation=conserveEvidence(pages);const structuralIssues=[...validationIssues,...conservation.issues];const hasFailure=structuralIssues.some(issue=>issue.severity==="failure")||arithmeticEvaluations.some(value=>value.outcome==="invented_evidence");const resultWithoutFingerprint={schemaVersion:1 as const,engineName:BUDGET_TABLE_RECONSTRUCTION_ENGINE_NAME,engineVersion:BUDGET_TABLE_RECONSTRUCTION_ENGINE_VERSION,profileId:BUDGET_TABLE_RECONSTRUCTION_PROFILE.profileId,profileVersion:BUDGET_TABLE_RECONSTRUCTION_PROFILE.profileVersion,sourceIdentity,status:hasFailure?"failed" as const:records.length===0?"insufficient_evidence" as const:records.some(record=>record.status!=="resolved")?"completed_with_ambiguities" as const:"completed" as const,pages,records,arithmeticEvaluations, evidenceDispositions:conservation.dispositions,structuralIssues,completeness:completeness(records,hasFailure),canonicalFingerprint:""};return{...resultWithoutFingerprint,canonicalFingerprint:fingerprintCanonical(resultWithoutFingerprint)}}
