import { addExact,equalExact,multiplyExact,rational } from "./budget-table-reconstruction-exact-rational";
import { fingerprintCanonical } from "./budget-table-reconstruction-fingerprint";
import type { ArithmeticEvaluation,ExactRational,ParsedNumericEvidence,ReconstructedBudgetRecord,ReconstructedLogicalRow } from "./budget-table-reconstruction.types";
function cellIds(value:ParsedNumericEvidence|null,rows:ReadonlyArray<ReconstructedLogicalRow>):string[]{if(!value)return[];const indices=new Set(value.sourceFragments.map(fragment=>`${fragment.locator.pageNumber}:${fragment.sourceTextItemIndex}`));return rows.flatMap(row=>row.cells).filter(cell=>cell.fragments.some(fragment=>indices.has(`${fragment.locator.pageNumber}:${fragment.sourceTextItemIndex}`))).map(cell=>cell.cellId)}
function evaluation(record:ReconstructedBudgetRecord,relation:ArithmeticEvaluation["relation"],values:ReadonlyArray<ParsedNumericEvidence|null>,displayed:ParsedNumericEvidence|null,computed:ExactRational|null,rows:ReadonlyArray<ReconstructedLogicalRow>,summands:ReadonlyArray<string>=[]):ArithmeticEvaluation{let outcome:ArithmeticEvaluation["outcome"]="not_applicable";if(values.some(value=>value===null)||displayed===null)outcome="missing_cell";else if(values.some(value=>value?.status==="ambiguous")||displayed.status==="ambiguous")outcome="insufficient_evidence";else if(values.some(value=>value?.status!=="resolved")||displayed.status!=="resolved"||computed===null||displayed.exactValue===null)outcome="insufficient_evidence";else outcome=equalExact(computed,displayed.exactValue)?"direct_correspondence":"source_arithmetic_inconsistency";return{evaluationId:`arithmetic:${fingerprintCanonical({recordId:record.recordId,relation})}`,relation,recordId:record.recordId,outcome,operandCellIds:[...new Set([...values,displayed].flatMap(value=>cellIds(value,rows)))].sort(),exactComputedValue:computed,displayedValue:displayed?.exactValue??null,summandRecordIds:[...summands]}}
export function evaluateArithmetic(records:ReadonlyArray<ReconstructedBudgetRecord>,rows:ReadonlyArray<ReconstructedLogicalRow>):ReadonlyArray<ArithmeticEvaluation>{const output:ArithmeticEvaluation[]=[];
 for(const record of records){if(record.kind==="service_item"){const q=record.quantity?.exactValue??null;const price=record.unitPrice?.exactValue??null;output.push(evaluation(record,"quantity_times_unit_price",[record.quantity,record.unitPrice],record.totalPrice,q&&price?multiplyExact(q,price):null,rows));const cost=record.unitCost?.exactValue??null;const bdi=record.bdiRate?.exactValue??null;const multiplier=bdi?addExact(rational(1n,1n),multiplyExact(bdi,rational(1n,100n))):null;output.push(evaluation(record,"unit_cost_with_bdi",[record.unitCost,record.bdiRate],record.unitPrice,cost&&multiplier?multiplyExact(cost,multiplier):null,rows))}
  if(record.kind==="subtotal"||record.kind==="total"){const descendants=records.filter(candidate=>candidate.parentRecordId===record.recordId&&candidate.totalPrice?.exactValue);let sum:ExactRational|null=descendants.length? rational(0n,1n):null;for(const child of descendants)sum=addExact(sum!,child.totalPrice!.exactValue!);output.push(evaluation(record,"descendant_sum",descendants.map(value=>value.totalPrice),record.totalPrice,sum,rows,descendants.map(value=>value.recordId)))}
 }return output;
}
